runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  TOMORROW_API_KEY: "iF22ZvwnCLNqJehEV3HVa4ZCW48IM0dR"

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto